### ISSUE TITLE
Doesn't work with docker-swarm

### ISSUE THREAD

**Issue by holms** [NexClipper/NexClipper#1]
Here's a swarm docker-compose.yml

```
    nexclipper:
      image: nexclipper/nexclipper
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker:/var/lib/docker
      networks:
        - main_traefik
      deploy:
        labels:
          - "traefik.port=9001"
          - "traefik.tags=monitoring"
          - "traefik.docker.network=main_traefik"
          - "traefik.backend=nexclipper"
          - "traefik.frontend.rule=Host:nexclipper.xxx.io"
        restart_policy:
            condition: on-failure
        replicas: 1
        placement:
          constraints:
            - node.role == manager

```

Here's a log output

```
2018-07-09T11:16:11.536847714Z ,
2018-07-09T11:16:11.544196386Z   .   ____          _            __ _ _,
2018-07-09T11:16:11.544423603Z  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \,
2018-07-09T11:16:11.544617701Z ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \,
2018-07-09T11:16:11.544808606Z  \\/  ___)| |_)| | | | | || (_| |  ) ) ) ),
2018-07-09T11:16:11.544996297Z   '  |____| .__|_| |_|_| |_\__, | / / / /,
2018-07-09T11:16:11.545182878Z  =========|_|==============|___/=/_/_/_/,
2018-07-09T11:16:11.549584698Z  :: Spring Boot ::        (v2.0.2.RELEASE),
2018-07-09T11:16:11.549757510Z ,
2018-07-09T11:16:11.957275175Z 2018-07-09 11:16:11.947  INFO 1 --- [           main] c.nexcloud.docker.ContainerApplication   : Starting ContainerApplication v0.0.1 on 58faa0c63617 with PID 1 (/NexClipper.war started by root in /),
2018-07-09T11:16:11.960871345Z 2018-07-09 11:16:11.960  INFO 1 --- [           main] c.nexcloud.docker.ContainerApplication   : No active profile set, falling back to default profiles: default,
2018-07-09T11:16:12.211552605Z 2018-07-09 11:16:12.211  INFO 1 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@3419866c: startup date [Mon Jul 09 11:16:12 GMT 2018]; root of context hierarchy,
2018-07-09T11:16:16.759416148Z 2018-07-09 11:16:16.759  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9001 (http),
2018-07-09T11:16:16.866885645Z 2018-07-09 11:16:16.866  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat],
2018-07-09T11:16:16.867638554Z 2018-07-09 11:16:16.867  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31,
2018-07-09T11:16:16.902426797Z 2018-07-09 11:16:16.902  INFO 1 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib],
2018-07-09T11:16:19.295166525Z 2018-07-09 11:16:19.294  INFO 1 --- [ost-startStop-1] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.,
2018-07-09T11:16:20.475557303Z 2018-07-09 11:16:20.475  INFO 1 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext,
2018-07-09T11:16:20.477768090Z 2018-07-09 11:16:20.477  INFO 1 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 8278 ms,
2018-07-09T11:16:20.880400793Z 2018-07-09 11:16:20.880  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/],
2018-07-09T11:16:20.891143218Z 2018-07-09 11:16:20.890  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*],
2018-07-09T11:16:20.891721816Z 2018-07-09 11:16:20.891  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*],
2018-07-09T11:16:20.891947361Z 2018-07-09 11:16:20.891  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*],
2018-07-09T11:16:20.892232324Z 2018-07-09 11:16:20.892  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*],
2018-07-09T11:16:21.320403934Z 2018-07-09 11:16:21.320  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler],
2018-07-09T11:16:22.001664928Z 2018-07-09 11:16:22.000  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@3419866c: startup date [Mon Jul 09 11:16:12 GMT 2018]; root of context hierarchy,
2018-07-09T11:16:22.196637006Z 2018-07-09 11:16:22.196  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/container_list]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerList(javax.servlet.http.HttpServletRequest,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.202795980Z 2018-07-09 11:16:22.197  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/detail]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerDetail(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.203365815Z 2018-07-09 11:16:22.203  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/stat]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerStat(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.203743689Z 2018-07-09 11:16:22.203  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/proc]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerProc(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.204535735Z 2018-07-09 11:16:22.203  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/net]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerNet(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.204936526Z 2018-07-09 11:16:22.204  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/env]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerEnv(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.206397412Z 2018-07-09 11:16:22.206  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/vol]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerVol(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.206742227Z 2018-07-09 11:16:22.206  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/log]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.containerLog(java.lang.String,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.208022915Z 2018-07-09 11:16:22.207  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/realtime_stat]}" onto public org.springframework.ui.ModelMap com.nexcloud.docker.controller.ContainerController.statHistory(java.lang.String,javax.servlet.http.HttpServletRequest,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.208667429Z 2018-07-09 11:16:22.208  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/containers/{container_id}/realtime_log]}" onto public org.springframework.ui.ModelMap com.nexcloud.docker.controller.ContainerController.logHistory(java.lang.String,javax.servlet.http.HttpServletRequest,org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.209260036Z 2018-07-09 11:16:22.209  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/]}" onto public org.springframework.web.servlet.ModelAndView com.nexcloud.docker.controller.ContainerController.index(org.springframework.ui.Model) throws java.lang.Exception,
2018-07-09T11:16:22.209606187Z 2018-07-09 11:16:22.209  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/check]}" onto public java.lang.String com.nexcloud.docker.controller.ContainerController.check(),
2018-07-09T11:16:22.229952510Z 2018-07-09 11:16:22.229  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse),
2018-07-09T11:16:22.230572856Z 2018-07-09 11:16:22.230  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest),
2018-07-09T11:16:22.308822468Z 2018-07-09 11:16:22.308  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler],
2018-07-09T11:16:22.315279337Z 2018-07-09 11:16:22.315  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler],
2018-07-09T11:16:22.902095330Z 2018-07-09 11:16:22.892  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup,
2018-07-09T11:16:23.052380199Z 2018-07-09 11:16:23.051  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9001 (http) with context path '',
2018-07-09T11:16:23.070916250Z 2018-07-09 11:16:23.057  INFO 1 --- [           main] c.nexcloud.docker.ContainerApplication   : Started ContainerApplication in 12.588 seconds (JVM running for 13.953),
2018-07-09T11:16:23.091218640Z 2018-07-09 11:16:23.085  INFO 1 --- [        Timer-0] com.nexcloud.docker.collector.Container  : ###### Container Start,
2018-07-09T11:16:23.092482520Z 2018-07-09 11:16:23.092  INFO 1 --- [        Timer-1] com.nexcloud.docker.util.Util            : curl --unix-socket /var/run/docker.sock  http:/v1.29/containers/json?all=true,
2018-07-09T11:16:23.100043604Z 2018-07-09 11:16:23.097  INFO 1 --- [        Timer-0] com.nexcloud.docker.util.Util            : curl --unix-socket /var/run/docker.sock  http:/v1.29/info,
2018-07-09T11:16:23.223376267Z Exception in thread "Timer-1" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 965 path $[0].NetworkSettings.Networks..IPAMConfig,
2018-07-09T11:16:23.223828933Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226),
2018-07-09T11:16:23.224468976Z 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41),
2018-07-09T11:16:23.224719555Z 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187),
2018-07-09T11:16:23.225618262Z 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145),
2018-07-09T11:16:23.228672932Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131),
2018-07-09T11:16:23.228686007Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222),
2018-07-09T11:16:23.228691945Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131),
2018-07-09T11:16:23.228697108Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222),
2018-07-09T11:16:23.228702143Z 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41),
2018-07-09T11:16:23.228706893Z 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82),
2018-07-09T11:16:23.228722313Z 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61),
2018-07-09T11:16:23.228728008Z 	at com.google.gson.Gson.fromJson(Gson.java:922),
2018-07-09T11:16:23.229932479Z 	at com.google.gson.Gson.fromJson(Gson.java:887),
2018-07-09T11:16:23.229944592Z 	at com.google.gson.Gson.fromJson(Gson.java:836),
2018-07-09T11:16:23.229949600Z 	at com.nexcloud.docker.collector.ContainerListThread.run(ContainerListThread.java:30),
2018-07-09T11:16:23.229954642Z 	at java.util.TimerThread.mainLoop(Timer.java:555),
2018-07-09T11:16:23.229959137Z 	at java.util.TimerThread.run(Timer.java:505),
2018-07-09T11:16:23.229963637Z Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 965 path $[0].NetworkSettings.Networks..IPAMConfig,
2018-07-09T11:16:23.229990661Z 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825),
2018-07-09T11:16:23.229996479Z 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402),
2018-07-09T11:16:23.230001151Z 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390),
2018-07-09T11:16:23.230593764Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131),
2018-07-09T11:16:23.230783080Z 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222),
2018-07-09T11:16:23.230952573Z 	... 16 more,
2018-07-09T11:16:33.089952035Z 2018-07-09 11:16:33.084  INFO 1 --- [        Timer-0] com.nexcloud.docker.collector.Container  : ###### Container Start,
2018-07-09T11:16:33.089973913Z 2018-07-09 11:16:33.085  INFO 1 --- [        Timer-0] com.nexcloud.docker.util.Util            : curl --unix-socket /var/run/docker.sock  http:/v1.29/info,
2018-07-09T11:16:43.089738597Z 2018-07-09 11:16:43.084  INFO 1 --- [        Timer-0] com.nexcloud.docker.collector.Container  : ###### Container Start,
2018-07-09T11:16:43.089762234Z 2018-07-09 11:16:43.084  INFO 1 --- [        Timer-0] com.nexcloud.docker.util.Util            : curl --unix-socket /var/run/docker.sock  http:/v1.29/info,
2018-07-09T11:16:53.089503889Z 2018-07-09 11:16:53.084  INFO 1 --- [        Timer-0] com.nexcloud.docker.collector.Container  : ###### Container Start,
2018-07-09T11:16:53.089540707Z 2018-07-09 11:16:53.084  INFO 1 --- [        Timer-0] com.nexcloud.docker.util.Util            : curl --unix-socket /var/run/docker.sock  http:/v1.29/info,
2018-07-09T11:17:03.088739278Z 2018-07-09 11:17:03.084  INFO 1 --- [        Timer-0] 
```

**Comment by jhhwang4195** [comment]
@holms
It should be working with following normal docker-compose.yml.
Sorry but we don't test Docker-swarm at this moment. 
Please check following docker-compose.yml again or run Docker in host direclty, it'll be run properly.

This is a command using docker run.
```
sudo docker run \
        --detach=true \
        --name NexClipper \
        -p 10001:9001 \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume /var/lib/docker:/var/lib/docker \
        nexclipper/nexclipper;
```

The following docker-compose.yml works normally.
```
version: "3"
services:
  nexclipper:
    image: nexclipper/nexclipper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    ports:
      - "10001:9001"
```

**Comment by holms** [comment]
It essentially did loaded but there's no information about containers. 
![screen](https://user-images.githubusercontent.com/280958/42498774-c5dd8e2a-8435-11e8-973e-3bf05720dfe2.png)

**Comment by jhhwang4195** [comment]
nexclipper uses the docker API to collect container information.
Can you tell me the result of the following command in swarm-master?
1. docker version
2. curl --unix-socket /var/run/docker.sock http:/v1.29/containers/json

**Comment by holms** [comment]
Version: Docker version 18.03.1-ce, build 9ee9f4

```
[
  {
    "Id": "0fb25055b9e7781fe5e619bd86cb738f7c51c0061704a75f9825cabc5f6b6a8a",
    "Names": [
      "/main_dd-agent.p3qbbg58u6paf1uskldfj62rx.nsdlyn832fsqi4h2b3v1j776v"
    ],
    "Image": "datadog/agent:latest@sha256:3926fb4957277d01ee1d2ef6733c5b99213b694e2ab127b0cc8d406d07e931d8",
    "ImageID": "sha256:b70e40670c449606848bb36b664c95a1048d52750b6adb6c49f1f64dce1864ac",
    "Command": "/init",
    "Created": 1531223270,
    "Ports": [
      {
        "PrivatePort": 8125,
        "Type": "udp"
      },
      {
        "PrivatePort": 8126,
        "Type": "tcp"
      }
    ],
    "Labels": {
      "com.docker.stack.namespace": "main",
      "com.docker.swarm.node.id": "p3qbbg58u6paf1uskldfj62rx",
      "com.docker.swarm.service.id": "joe9l85l586vrf0f6ihb4901s",
      "com.docker.swarm.service.name": "main_dd-agent",
      "com.docker.swarm.task": "",
      "com.docker.swarm.task.id": "nsdlyn832fsqi4h2b3v1j776v",
      "com.docker.swarm.task.name": "main_dd-agent.p3qbbg58u6paf1uskldfj62rx.nsdlyn832fsqi4h2b3v1j776v",
      "maintainer": "Datadog <package@datadoghq.com>"
    },
    "State": "running",
    "Status": "Up 34 minutes (healthy)",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "main_traefik": {
          "IPAMConfig": {
            "IPv4Address": "10.0.0.61"
          },
          "Links": null,
          "Aliases": null,
          "NetworkID": "kjxw8zm8gtn8moprvwhsks8jl",
          "EndpointID": "b38e220b436f051be49ab1f81c8995c003615d867acf3537d393b95afb320dcb",
          "Gateway": "",
          "IPAddress": "10.0.0.61",
          "IPPrefixLen": 24,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:0a:00:00:3d",
          "DriverOpts": null
        }
      }
    },
    "Mounts": [
      {
        "Type": "bind",
        "Source": "/sys/fs/cgroup",
        "Destination": "/host/sys/fs/cgroup",
        "Mode": "",
        "RW": false,
        "Propagation": "rprivate"
      },
      {
        "Type": "bind",
        "Source": "/var/run/docker.sock",
        "Destination": "/var/run/docker.sock",
        "Mode": "",
        "RW": false,
        "Propagation": "rprivate"
      },
      {
        "Type": "bind",
        "Source": "/proc",
        "Destination": "/host/proc",
        "Mode": "",
        "RW": false,
        "Propagation": "rprivate"
      }
    ]
  },
  {
    "Id": "2d8acd3207e7099d48291a17bba509fbb5fcdf48ead5debebedbeb6753cde014",
    "Names": [
      "/mon_nexclipper.1.7icl3no51bfyead0a03i41e84"
    ],
    "Image": "nexclipper/nexclipper:latest@sha256:e9d0591bf30844f6d971835368a4fd047fb1384cb358850f475d716ed52414c9",
    "ImageID": "sha256:ed4716a1e1019b3dd951f49ee62d183b47b258f0da944b3dc1dc7eb399b4b850",
    "Command": "/bin/sh -c 'exec java -jar -Djava.security.egd=file:/dev/./urandom -jar /NexClipper.war'",
    "Created": 1531135768,
    "Ports": [],
    "Labels": {
      "com.docker.stack.namespace": "mon",
      "com.docker.swarm.node.id": "p3qbbg58u6paf1uskldfj62rx",
      "com.docker.swarm.service.id": "5a3frw60avx8hl9k5gfalgpyo",
      "com.docker.swarm.service.name": "mon_nexclipper",
      "com.docker.swarm.task": "",
      "com.docker.swarm.task.id": "7icl3no51bfyead0a03i41e84",
      "com.docker.swarm.task.name": "mon_nexclipper.1.7icl3no51bfyead0a03i41e84"
    },
    "State": "running",
    "Status": "Up 25 hours",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "main_traefik": {
          "IPAMConfig": {
            "IPv4Address": "10.0.0.91"
          },
          "Links": null,
          "Aliases": null,
          "NetworkID": "kjxw8zm8gtn8moprvwhsks8jl",
          "EndpointID": "cf09875e96b61edd94047694ad33cca3b9d9d0f472dc5b52dc22da20a4ba6945",
          "Gateway": "",
          "IPAddress": "10.0.0.91",
          "IPPrefixLen": 24,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:0a:00:00:5b",
          "DriverOpts": null
        }
      }
    },
    "Mounts": [
      {
        "Type": "volume",
        "Name": "1b844616a253c0b4ec14bfcae6359fdfffaa67e5131989f44e4be9f8329e13b8",
        "Source": "",
        "Destination": "/tmp",
        "Driver": "local",
        "Mode": "",
        "RW": true,
        "Propagation": ""
      },
      {
        "Type": "bind",
        "Source": "/var/lib/docker",
        "Destination": "/var/lib/docker",
        "Mode": "",
        "RW": true,
        "Propagation": "rslave"
      },
      {
        "Type": "bind",
        "Source": "/var/run/docker.sock",
        "Destination": "/var/run/docker.sock",
        "Mode": "",
        "RW": true,
        "Propagation": "rprivate"
      }
    ]
  },
  {
    "Id": "5093c840474d24e2c138d574818864643154b22f6ffcf747dfe8368106e3e1da",
    "Names": [
      "/mon_visualizer.1.fkhgnly9byr3vxoxtbhouoncg"
    ],
    "Image": "dockersamples/visualizer:latest@sha256:1e8dd2a3c72166f38c4cc28071caa08c60574691371f8b18123fdb3412a6de75",
    "ImageID": "sha256:5262886a4d4c7cb537b0c40778177a29ef016bd031c899ddb08eb2f935cad5f2",
    "Command": "npm start",
    "Created": 1529926636,
    "Ports": [
      {
        "PrivatePort": 8080,
        "Type": "tcp"
      }
    ],
    "Labels": {
      "com.docker.stack.namespace": "mon",
      "com.docker.swarm.node.id": "p3qbbg58u6paf1uskldfj62rx",
      "com.docker.swarm.service.id": "3ail9xwh4jgtnq3g9saj47pvc",
      "com.docker.swarm.service.name": "mon_visualizer",
      "com.docker.swarm.task": "",
      "com.docker.swarm.task.id": "fkhgnly9byr3vxoxtbhouoncg",
      "com.docker.swarm.task.name": "mon_visualizer.1.fkhgnly9byr3vxoxtbhouoncg"
    },
    "State": "running",
    "Status": "Up 2 weeks (healthy)",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "main_traefik": {
          "IPAMConfig": {
            "IPv4Address": "10.0.0.16"
          },
          "Links": null,
          "Aliases": null,
          "NetworkID": "kjxw8zm8gtn8moprvwhsks8jl",
          "EndpointID": "c2293b02ef76cfd021c4cea6c1ef9b330a6959d72da22d2166872157f2c775ba",
          "Gateway": "",
          "IPAddress": "10.0.0.16",
          "IPPrefixLen": 24,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:0a:00:00:10",
          "DriverOpts": null
        }
      }
    },
    "Mounts": [
      {
        "Type": "bind",
        "Source": "/var/run/docker.sock",
        "Destination": "/var/run/docker.sock",
        "Mode": "",
        "RW": true,
        "Propagation": "rprivate"
      }
    ]
  }
]
```

And this is just for master, what about other nodes :)? You're almost the only one from simple web dashboards out there who shows memory usage of containers

**Comment by nexclouding** [comment]
This version of NexClipper is now light one just for each host level to monitor docker instantly without longterm data, and not for container cluster level. But it provide almost necessary information to monitor docker.
If you see container detail ui, you can find many tab for more information, not just for memory usage.

[Container Detail UI -> Tab]
- Stats:  CPU, Memeoy, Network, Network error, Block IO
- Process
- Networks
- Environment
- Volumes
- Logs

We'll announce SaaS version which support k8s, mesos at August.

Thanks

**Comment by jhhwang4195** [comment]
@holms 
nexclipper/nexclipper image has been pushed again.
Can you pull the latest docker image and test it?
Is the container information displayed normally?

**Comment by holms** [comment]
@jhhwang4195 thank you very much! It does work! Having whole cluster containers would be a real bliss. Really waiting for updates, although I might send some PR also, because I'm really interested in such real time monitoring of all containers, using datadog for this is a bit overkill. The only possible solution for now is to use Docker EE which is not something I'd like go with. 
![screen](https://user-images.githubusercontent.com/280958/42617041-035bca6c-85b9-11e8-8494-a132fa8dae70.png)
